## 通过下面的配置，启用所有的监控端点，默认情况下、这些端点禁用
management: 
  endpoints: 
   web: 
     exposure: 
       include: "*"
spring:
### 
  profiles: 
    active: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/books?useUnicode=true&characterEncoding=utf-8
    username: root
    password: feixiang
    driver-class-name: com.mysql.jdbc.Driver
server: 
  #端口号
  port: 8888
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##PageHelper配置
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
## 自定义key
disconf: 
  name: 名字
info: 
  name: actuator/info
  sex: 男
  age: 123


# MQ配置
apache:
  rocketmq:
#消费者的配置
    consumer:
      pushConsumer: XiaourPushConsumer
#生产者的配置
    producer:
      producerGroup: Xiaour
#Nameserver的地址,这里配置你MQ安装的机器上的IP就好，我这里在本机安装的
    namesrvAddr: 127.0.0.1:9876